# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeWork' do
  use_frameworks!

  target 'HomeWorkTests' do
    inherit! :search_paths
  end

  target 'HomeWorkUITests' do
    end


pod 'Alamofire'
pod 'SDWebImage', '~> 5.0'
pod 'RealmSwift', '~>10'



end
